[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:celery-worker]
command=celery -A app.celery_app worker --loglevel=info --pool=solo --concurrency=1
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/celery-worker.log
stderr_logfile=/var/log/supervisor/celery-worker_error.log
environment=PYTHONPATH="/app"

[program:celery-beat]
command=celery -A app.celery_app beat --loglevel=info
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/celery-beat.log
stderr_logfile=/var/log/supervisor/celery-beat_error.log
environment=PYTHONPATH="/app"

[program:uvicorn]
command=uvicorn app.main:app --host 0.0.0.0 --port 8004
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=PYTHONPATH="/app"